/** Thin GraphQL delegation for the administrative namespace. */
import {
  cancelRecoveryCase,
  addInternalNote,
  addTtmAgendaItem,
  adminDocumentDownloadUrl,
  archiveProgrammeCycle,
  changeFundingAward,
  cancelRevisionRequest,
  cancelTtmMeeting,
  changeOpenCycleClosingTime,
  claimApplication,
  cancelBankReferral,
  closeProgrammeCycle,
  closeRecoveryCase,
  completeDeskReview,
  correctBankOutcome,
  correctTtmDecision,
  createFundingAward,
  createProgrammeCycle,
  createTtmMeeting,
  finalizeTtmMeeting,
  fundingByApplication,
  intakeByReference,
  intakeQueue,
  intakeQueues,
  intakeWorkspace,
  openProgrammeCycle,
  openRecoveryCase,
  programmeCycleApplicationCounts,
  programmeCycleById,
  programmeCycleEvents,
  programmeCycles,
  reassignApplication,
  removeTtmAgendaItem,
  recordBankOutcome,
  recordFundingAssessment,
  recordFundingRelease,
  recordRecoveryEntry,
  recordTtmDecision,
  recoveryById,
  referApplicationToBank,
  releaseApplication,
  reverseFundingRelease,
  reorderTtmAgendaItem,
  setProgrammeCycleDeleted,
  startDeskReview,
  startTtmMeeting,
  ttmMeetingById,
  ttmMeetings,
  updateDraftProgrammeCycleController,
  updateOpenCycleGuidance,
  updateTtmMeeting,
} from '../../../services/admin'
import type { GraphQLContext } from '../../types'
import { snapshotRecordToPublic } from '../../../services/application/queries/application'

type Args<T> = { input: T }

export const adminResolvers = {
  Query: { admin: () => ({}) },
  Mutation: { admin: () => ({}) },
  AdminQuery: {
    programmeCycle: () => ({}),
    intake: () => ({}),
    decision: () => ({}),
    funding: () => ({}),
  },
  AdminMutation: {
    programmeCycle: () => ({}),
    intake: () => ({}),
    decision: () => ({}),
    funding: () => ({}),
  },
  AdminProgrammeCycleQuery: {
    list: (_parent: unknown, args: Parameters<typeof programmeCycles>[0], context: GraphQLContext) => programmeCycles(args, context),
    byId: (_parent: unknown, args: { id: string }, context: GraphQLContext) => programmeCycleById(args.id, context),
    counts: (_parent: unknown, args: { id: string }, context: GraphQLContext) => programmeCycleApplicationCounts(args.id, context),
    events: (_parent: unknown, args: { id: string; first?: number }, context: GraphQLContext) => programmeCycleEvents(args, context),
  },
  AdminIntakeQuery: {
    queue: (_parent: unknown, args: { input?: Parameters<typeof intakeQueue>[0] }, context: GraphQLContext) => intakeQueue(args.input ?? {}, context),
    queues: (_parent: unknown, args: { cycleId?: string | null }, context: GraphQLContext) => intakeQueues(args.cycleId, context),
    byReference: (_parent: unknown, args: { referenceNumber: string }, context: GraphQLContext) => intakeByReference(args.referenceNumber, context),
    workspace: (_parent: unknown, args: { applicationId: string }, context: GraphQLContext) => intakeWorkspace(args.applicationId, context),
    documentDownloadUrl: (_parent: unknown, args: { applicationId: string; submissionDocumentId: string }, context: GraphQLContext) => adminDocumentDownloadUrl(args, context),
  },
  AdminDecisionQuery: {
    meetings: (_parent: unknown, args: Parameters<typeof ttmMeetings>[0], context: GraphQLContext) => ttmMeetings(args, context),
    meetingById: (_parent: unknown, args: { meetingId: string }, context: GraphQLContext) => ttmMeetingById(args.meetingId, context),
  },
  AdminFundingQuery: {
    byApplication: (_parent: unknown, args: { applicationId: string }, context: GraphQLContext) => fundingByApplication(args.applicationId, context),
    recoveryById: (_parent: unknown, args: { recoveryCaseId: string }, context: GraphQLContext) => recoveryById(args.recoveryCaseId, context),
  },
  AdminProgrammeCycleMutation: {
    create: (_parent: unknown, args: Args<Parameters<typeof createProgrammeCycle>[0]>, context: GraphQLContext) => createProgrammeCycle(args.input, context),
    updateDraft: (_parent: unknown, args: Args<{ id: string; expectedVersion: number; reason: string; cycle: Parameters<typeof createProgrammeCycle>[0] }>, context: GraphQLContext) => updateDraftProgrammeCycleController({ ...args.input.cycle, id: args.input.id, expectedVersion: args.input.expectedVersion, reason: args.input.reason }, context),
    open: (_parent: unknown, args: Args<Parameters<typeof openProgrammeCycle>[0]>, context: GraphQLContext) => openProgrammeCycle(args.input, context),
    updateOpenGuidance: (_parent: unknown, args: Args<Parameters<typeof updateOpenCycleGuidance>[0]>, context: GraphQLContext) => updateOpenCycleGuidance(args.input, context),
    changeClosingTime: (_parent: unknown, args: Args<Parameters<typeof changeOpenCycleClosingTime>[0]>, context: GraphQLContext) => changeOpenCycleClosingTime(args.input, context),
    close: (_parent: unknown, args: Args<Parameters<typeof closeProgrammeCycle>[0]>, context: GraphQLContext) => closeProgrammeCycle(args.input, context),
    archive: (_parent: unknown, args: Args<Parameters<typeof archiveProgrammeCycle>[0]>, context: GraphQLContext) => archiveProgrammeCycle(args.input, context),
    softDeleteDraft: (_parent: unknown, args: Args<{ id: string; expectedVersion: number; reason: string }>, context: GraphQLContext) => setProgrammeCycleDeleted(args.input, context, true),
    restoreDraft: (_parent: unknown, args: { id: string; expectedVersion: number }, context: GraphQLContext) => setProgrammeCycleDeleted({ ...args, reason: '' }, context, false),
  },
  AdminIntakeMutation: {
    claim: (_parent: unknown, args: Args<Parameters<typeof claimApplication>[0]>, context: GraphQLContext) => claimApplication(args.input, context),
    release: (_parent: unknown, args: Args<Parameters<typeof releaseApplication>[0]>, context: GraphQLContext) => releaseApplication(args.input, context),
    reassign: (_parent: unknown, args: Args<Parameters<typeof reassignApplication>[0]>, context: GraphQLContext) => reassignApplication(args.input, context),
    addInternalNote: (_parent: unknown, args: Args<Parameters<typeof addInternalNote>[0]>, context: GraphQLContext) => addInternalNote(args.input, context),
    startDeskReview: (_parent: unknown, args: Args<Parameters<typeof startDeskReview>[0]>, context: GraphQLContext) => startDeskReview(args.input, context),
    completeDeskReview: (_parent: unknown, args: Args<Parameters<typeof completeDeskReview>[0]>, context: GraphQLContext) => completeDeskReview(args.input, context),
    cancelRevision: (_parent: unknown, args: Args<Parameters<typeof cancelRevisionRequest>[0]>, context: GraphQLContext) => cancelRevisionRequest(args.input, context),
  },
  AdminDecisionMutation: {
    referToBank: (_parent: unknown, args: Args<Parameters<typeof referApplicationToBank>[0]>, context: GraphQLContext) => referApplicationToBank(args.input, context),
    cancelBankReferral: (_parent: unknown, args: Args<Parameters<typeof cancelBankReferral>[0]>, context: GraphQLContext) => cancelBankReferral(args.input, context),
    recordBankOutcome: (_parent: unknown, args: Args<Parameters<typeof recordBankOutcome>[0]>, context: GraphQLContext) => recordBankOutcome(args.input, context),
    correctBankOutcome: (_parent: unknown, args: Args<Parameters<typeof correctBankOutcome>[0]>, context: GraphQLContext) => correctBankOutcome(args.input, context),
    createMeeting: (_parent: unknown, args: Args<Parameters<typeof createTtmMeeting>[0]>, context: GraphQLContext) => createTtmMeeting(args.input, context),
    updateMeeting: (_parent: unknown, args: Args<Parameters<typeof updateTtmMeeting>[0]>, context: GraphQLContext) => updateTtmMeeting(args.input, context),
    cancelMeeting: (_parent: unknown, args: Args<Parameters<typeof cancelTtmMeeting>[0]>, context: GraphQLContext) => cancelTtmMeeting(args.input, context),
    addAgendaItem: (_parent: unknown, args: Args<Parameters<typeof addTtmAgendaItem>[0]>, context: GraphQLContext) => addTtmAgendaItem(args.input, context),
    reorderAgendaItem: (_parent: unknown, args: Args<Parameters<typeof reorderTtmAgendaItem>[0]>, context: GraphQLContext) => reorderTtmAgendaItem(args.input, context),
    removeAgendaItem: (_parent: unknown, args: Args<Parameters<typeof removeTtmAgendaItem>[0]>, context: GraphQLContext) => removeTtmAgendaItem(args.input, context),
    startMeeting: (_parent: unknown, args: Args<Parameters<typeof startTtmMeeting>[0]>, context: GraphQLContext) => startTtmMeeting(args.input, context),
    finalizeMeeting: (_parent: unknown, args: Args<Parameters<typeof finalizeTtmMeeting>[0]>, context: GraphQLContext) => finalizeTtmMeeting(args.input, context),
    recordDecision: (_parent: unknown, args: Args<Parameters<typeof recordTtmDecision>[0]>, context: GraphQLContext) => recordTtmDecision(args.input, context),
    correctDecision: (_parent: unknown, args: Args<Parameters<typeof correctTtmDecision>[0]>, context: GraphQLContext) => correctTtmDecision(args.input, context),
  },
  AdminFundingMutation: {
    createAward: (_parent: unknown, args: Args<Parameters<typeof createFundingAward>[0]>, context: GraphQLContext) => createFundingAward(args.input, context),
    changeAward: (_parent: unknown, args: Args<Parameters<typeof changeFundingAward>[0]>, context: GraphQLContext) => changeFundingAward(args.input, context),
    recordRelease: (_parent: unknown, args: Args<Parameters<typeof recordFundingRelease>[0]>, context: GraphQLContext) => recordFundingRelease(args.input, context),
    reverseRelease: (_parent: unknown, args: Args<Parameters<typeof reverseFundingRelease>[0]>, context: GraphQLContext) => reverseFundingRelease(args.input, context),
    recordAssessment: (_parent: unknown, args: Args<Parameters<typeof recordFundingAssessment>[0]>, context: GraphQLContext) => recordFundingAssessment(args.input, context),
    openRecovery: (_parent: unknown, args: Args<Parameters<typeof openRecoveryCase>[0]>, context: GraphQLContext) => openRecoveryCase(args.input, context),
    recordRecoveryEntry: (_parent: unknown, args: Args<Parameters<typeof recordRecoveryEntry>[0]>, context: GraphQLContext) => recordRecoveryEntry(args.input, context),
    cancelRecovery: (_parent: unknown, args: Args<Parameters<typeof cancelRecoveryCase>[0]>, context: GraphQLContext) => cancelRecoveryCase(args.input, context),
    closeRecovery: (_parent: unknown, args: Args<Parameters<typeof closeRecoveryCase>[0]>, context: GraphQLContext) => closeRecoveryCase(args.input, context),
  },
  AdminWorkspace: {
    notes: (parent: { internalNotes?: unknown[] }) => parent.internalNotes ?? [],
    snapshots: (parent: { snapshots: Parameters<typeof snapshotRecordToPublic>[0][] }) =>
      parent.snapshots.map(snapshotRecordToPublic),
    documents: (parent: { documents: Array<{ pin: Record<string, unknown>; file: Record<string, unknown> }> }) =>
      parent.documents.map(({ pin, file }) => ({ ...pin, ...file, id: pin.id })),
    reviewChecks: (parent: { reviewChecks: Array<{ check: unknown }> }) =>
      parent.reviewChecks.map(({ check }) => check),
    releases: (parent: { releases: Array<{ entry: unknown }> }) =>
      parent.releases.map(({ entry }) => entry),
    assessments: (parent: { assessments: Array<{ assessment: unknown }> }) =>
      parent.assessments.map(({ assessment }) => assessment),
  },
}
