/*
 * Generated by `node scripts/check-workflow-catalog.mjs --write` from
 * workflow.json. Do not edit; `npm run check:workflow-catalog` fails on drift.
 */

export const inputFieldTypes = [
  'TEXT',
  'LONG_TEXT',
  'DATE',
  'INTEGER',
  'MONEY_PAISE',
  'BOOLEAN',
  'SINGLE_CHOICE',
  'MULTI_CHOICE',
  'STATEMENT',
] as const
export type InputFieldType = (typeof inputFieldTypes)[number]

export const conditionSources = [
  'ANSWER',
  'STATUS_FLAG',
  'RECORDED_VALUE',
  'INPUT',
] as const
export type ConditionSource = (typeof conditionSources)[number]

export const paramKinds = [
  'STAGE_KEY',
  'STATUS_FLAG_KEY',
  'INPUT_KEY',
  'ANSWER_KEY',
  'RECORDED_VALUE_KEY',
  'CHOICE_ROUTES',
  'TEXT',
  'BOOLEAN',
  'COUNT',
  'MONEY_PAISE',
  'APPLICATION_KIND_KEY',
  'PIPELINE_KEY',
] as const
export type ParamKind = (typeof paramKinds)[number]

const formRuleTypes = [
  'AT_LEAST_ONE_TRUE',
  'DIFFERENT_VALUES',
  'SUM_AT_MOST',
  'AT_MOST_FIELD',
] as const
export type FormRuleType = (typeof formRuleTypes)[number]

const eligibilityRuleTypes = [
  'PRIOR_APPLICATION_HAS_FLAG',
  'PRIOR_RECORDED_VALUE_AT_LEAST',
  'NO_OPEN_APPLICATION_OF_KIND',
  'MAX_APPLICATIONS_OF_KIND',
  'ENTERPRISE_AGE_AT_LEAST',
] as const
export type EligibilityRuleType = (typeof eligibilityRuleTypes)[number]

export const effectTypes = [
  'ADD_STATUS',
  'REMOVE_STATUS',
  'SET_RECORDED_VALUE',
  'REQUEST_REVISION',
  'NOTIFY_APPLICANT',
  'ADD_INTERNAL_NOTE',
  'MOVE_TO_STAGE',
  'MOVE_BY_CHOICE',
  'RETURN_TO_PREVIOUS',
  'COMPLETE_PIPELINE',
  'CLOSE_APPLICATION',
] as const
export type EffectType = (typeof effectTypes)[number]

export type CatalogueParam = {
  readonly name: string
  readonly kind: ParamKind
  readonly required: boolean
  readonly description: string
}

export type EffectEntry = {
  readonly group: 'APPLICATION' | 'STAGE'
  readonly description: string
  readonly permission: string | null
  readonly exclusive: 'STAGE' | 'LIFECYCLE' | null
  readonly terminal: boolean
  readonly params: readonly CatalogueParam[]
}

export const effectCatalogue: Record<EffectType, EffectEntry> = {
  "ADD_STATUS": {
    "group": "APPLICATION",
    "description": "Adds a status flag. A flag that ends the pipeline is added by COMPLETE_PIPELINE or CLOSE_APPLICATION instead.",
    "permission": "BY_FLAG_KIND",
    "exclusive": null,
    "terminal": false,
    "params": [
      {
        "name": "flag",
        "kind": "STATUS_FLAG_KEY",
        "required": true,
        "description": "The flag to add."
      }
    ]
  },
  "REMOVE_STATUS": {
    "group": "APPLICATION",
    "description": "Removes a status flag.",
    "permission": "BY_FLAG_KIND",
    "exclusive": null,
    "terminal": false,
    "params": [
      {
        "name": "flag",
        "kind": "STATUS_FLAG_KEY",
        "required": true,
        "description": "The flag to remove."
      }
    ]
  },
  "SET_RECORDED_VALUE": {
    "group": "APPLICATION",
    "description": "Keeps what the officer entered as a named value on the application, such as the approved grant.",
    "permission": "stage:decide",
    "exclusive": null,
    "terminal": false,
    "params": [
      {
        "name": "input",
        "kind": "INPUT_KEY",
        "required": true,
        "description": "The input whose value is kept."
      },
      {
        "name": "target",
        "kind": "RECORDED_VALUE_KEY",
        "required": true,
        "description": "The name it is kept under."
      },
      {
        "name": "atMostAnswer",
        "kind": "ANSWER_KEY",
        "required": false,
        "description": "It may not exceed the applicant's answer to this question."
      },
      {
        "name": "atMostCycleCeiling",
        "kind": "BOOLEAN",
        "required": false,
        "description": "It may not exceed the cycle's funding ceiling."
      }
    ]
  },
  "REQUEST_REVISION": {
    "group": "APPLICATION",
    "description": "Asks the applicant to correct the form stages the officer names. When they resubmit, the application returns to this stage.",
    "permission": "stage:request_revision",
    "exclusive": "LIFECYCLE",
    "terminal": false,
    "params": [
      {
        "name": "flag",
        "kind": "STATUS_FLAG_KEY",
        "required": true,
        "description": "The flag held while the applicant corrects it; it must allow revision-scoped editing."
      }
    ]
  },
  "NOTIFY_APPLICANT": {
    "group": "APPLICATION",
    "description": "Tells the applicant, on their timeline and by email when asked to.",
    "permission": null,
    "exclusive": null,
    "terminal": false,
    "params": [
      {
        "name": "message",
        "kind": "TEXT",
        "required": true,
        "description": "What the applicant reads."
      },
      {
        "name": "email",
        "kind": "BOOLEAN",
        "required": false,
        "description": "Also send it by email."
      }
    ]
  },
  "ADD_INTERNAL_NOTE": {
    "group": "APPLICATION",
    "description": "Keeps what the officer wrote as a staff-only note on the application.",
    "permission": "application:note",
    "exclusive": null,
    "terminal": false,
    "params": [
      {
        "name": "input",
        "kind": "INPUT_KEY",
        "required": true,
        "description": "The long-text input holding the note."
      }
    ]
  },
  "MOVE_TO_STAGE": {
    "group": "STAGE",
    "description": "Sends the application to another stage.",
    "permission": "stage:advance",
    "exclusive": "STAGE",
    "terminal": false,
    "params": [
      {
        "name": "target",
        "kind": "STAGE_KEY",
        "required": true,
        "description": "The stage it goes to."
      }
    ]
  },
  "MOVE_BY_CHOICE": {
    "group": "STAGE",
    "description": "Sends the application to the stage chosen by one of the action's inputs — for example, the bank.",
    "permission": "stage:advance",
    "exclusive": "STAGE",
    "terminal": false,
    "params": [
      {
        "name": "input",
        "kind": "INPUT_KEY",
        "required": true,
        "description": "The single-choice input that decides."
      },
      {
        "name": "routes",
        "kind": "CHOICE_ROUTES",
        "required": true,
        "description": "Where each option sends it; every option must be routed."
      }
    ]
  },
  "RETURN_TO_PREVIOUS": {
    "group": "STAGE",
    "description": "Sends the application back to the stage it actually came from.",
    "permission": "stage:return",
    "exclusive": "STAGE",
    "terminal": false,
    "params": []
  },
  "COMPLETE_PIPELINE": {
    "group": "STAGE",
    "description": "Finishes the application's journey successfully, with a flag that ends the pipeline.",
    "permission": "stage:advance",
    "exclusive": "STAGE",
    "terminal": true,
    "params": [
      {
        "name": "flag",
        "kind": "STATUS_FLAG_KEY",
        "required": true,
        "description": "The terminal flag it finishes with."
      }
    ]
  },
  "CLOSE_APPLICATION": {
    "group": "STAGE",
    "description": "Ends the application's journey without success, such as a rejection, with a flag that ends the pipeline.",
    "permission": "stage:close",
    "exclusive": "STAGE",
    "terminal": true,
    "params": [
      {
        "name": "flag",
        "kind": "STATUS_FLAG_KEY",
        "required": true,
        "description": "The terminal flag it closes with."
      }
    ]
  }
}

export type FormRuleEntry = {
  readonly description: string
  readonly operandTypes: readonly string[]
  readonly minOperands: number
  readonly maxOperands: number
  readonly limit: 'NONE' | 'REQUIRED'
}

export const formRuleCatalogue: Record<FormRuleType, FormRuleEntry> = {
  "AT_LEAST_ONE_TRUE": {
    "description": "At least one of these yes-or-no questions must be answered yes — for example, a grant, a loan, or both.",
    "operandTypes": [
      "BOOLEAN",
      "ATTESTATION"
    ],
    "minOperands": 2,
    "maxOperands": 8,
    "limit": "NONE"
  },
  "DIFFERENT_VALUES": {
    "description": "These answers must all differ — for example, a first and a second choice of bank.",
    "operandTypes": [
      "SINGLE_CHOICE",
      "TEXT",
      "EMAIL",
      "PHONE"
    ],
    "minOperands": 2,
    "maxOperands": 8,
    "limit": "NONE"
  },
  "SUM_AT_MOST": {
    "description": "These amounts together may not exceed a fixed limit.",
    "operandTypes": [
      "MONEY_PAISE",
      "INTEGER"
    ],
    "minOperands": 1,
    "maxOperands": 8,
    "limit": "REQUIRED"
  },
  "AT_MOST_FIELD": {
    "description": "The first answer may not exceed the second — for example, a loan asked for may not exceed the project's cost.",
    "operandTypes": [
      "MONEY_PAISE",
      "INTEGER",
      "DATE"
    ],
    "minOperands": 2,
    "maxOperands": 2,
    "limit": "NONE"
  }
}

export type EligibilityEntry = {
  readonly description: string
  readonly params: readonly CatalogueParam[]
}

export const eligibilityCatalogue: Record<EligibilityRuleType, EligibilityEntry> = {
  "PRIOR_APPLICATION_HAS_FLAG": {
    "description": "The enterprise has an earlier application that holds a status flag, held for at least a number of months.",
    "params": [
      {
        "name": "flag",
        "kind": "STATUS_FLAG_KEY",
        "required": true,
        "description": "The flag the earlier application must hold."
      },
      {
        "name": "pipelineKey",
        "kind": "PIPELINE_KEY",
        "required": false,
        "description": "Only earlier applications worked in this pipeline."
      },
      {
        "name": "minMonthsSinceFlag",
        "kind": "COUNT",
        "required": false,
        "description": "How long ago, at least, the flag must have been added."
      }
    ]
  },
  "PRIOR_RECORDED_VALUE_AT_LEAST": {
    "description": "An earlier application of the enterprise recorded a value of at least an amount.",
    "params": [
      {
        "name": "value",
        "kind": "RECORDED_VALUE_KEY",
        "required": true,
        "description": "The recorded value to read."
      },
      {
        "name": "amountPaise",
        "kind": "MONEY_PAISE",
        "required": true,
        "description": "The least it must be."
      }
    ]
  },
  "NO_OPEN_APPLICATION_OF_KIND": {
    "description": "The enterprise has no unfinished application of a kind — a draft, or one still being worked.",
    "params": [
      {
        "name": "kind",
        "kind": "APPLICATION_KIND_KEY",
        "required": true,
        "description": "The kind that must have no open application."
      }
    ]
  },
  "MAX_APPLICATIONS_OF_KIND": {
    "description": "The enterprise has made fewer than a number of applications of a kind, across every cycle.",
    "params": [
      {
        "name": "kind",
        "kind": "APPLICATION_KIND_KEY",
        "required": true,
        "description": "The kind to count."
      },
      {
        "name": "max",
        "kind": "COUNT",
        "required": true,
        "description": "How many are allowed in all."
      }
    ]
  },
  "ENTERPRISE_AGE_AT_LEAST": {
    "description": "The enterprise was established at least a number of months ago.",
    "params": [
      {
        "name": "months",
        "kind": "COUNT",
        "required": true,
        "description": "The least age, in whole months."
      }
    ]
  }
}

/** Every entry's description, for the pipeline editor and the API. */
export const workflowDescriptions: Record<string, string> = {
  "inputFieldTypes.TEXT": "A short line of text, such as a reference number.",
  "inputFieldTypes.LONG_TEXT": "A paragraph, such as a note to the next stage. Never copied into the activity history.",
  "inputFieldTypes.DATE": "A calendar date.",
  "inputFieldTypes.INTEGER": "A whole number.",
  "inputFieldTypes.MONEY_PAISE": "An amount of money, entered in rupees and kept in paise.",
  "inputFieldTypes.BOOLEAN": "Yes or no.",
  "inputFieldTypes.SINGLE_CHOICE": "One of a fixed list of options, such as a bank.",
  "inputFieldTypes.MULTI_CHOICE": "Any of a fixed list of options.",
  "inputFieldTypes.STATEMENT": "Text shown to the officer, with no answer.",
  "conditionSources.ANSWER": "An answer the applicant gave on the submitted form.",
  "conditionSources.STATUS_FLAG": "Whether the application currently holds a status flag.",
  "conditionSources.RECORDED_VALUE": "A value an earlier action recorded on the application.",
  "conditionSources.INPUT": "What the officer entered into this action's own inputs.",
  "paramKinds.STAGE_KEY": "A stage of the same pipeline.",
  "paramKinds.STATUS_FLAG_KEY": "A status flag the pipeline declares.",
  "paramKinds.INPUT_KEY": "One of the action's own input fields.",
  "paramKinds.ANSWER_KEY": "A question on the form of any cycle that pins the pipeline; checked when the cycle opens.",
  "paramKinds.RECORDED_VALUE_KEY": "A recorded value the pipeline declares.",
  "paramKinds.CHOICE_ROUTES": "For each option of a choice input, the stage it sends the application to.",
  "paramKinds.TEXT": "Fixed text written by the author, such as a message to the applicant.",
  "paramKinds.BOOLEAN": "A yes or no setting.",
  "paramKinds.COUNT": "A whole number of zero or more.",
  "paramKinds.MONEY_PAISE": "A fixed amount of money, in paise.",
  "paramKinds.APPLICATION_KIND_KEY": "A kind of application the cycle declares.",
  "paramKinds.PIPELINE_KEY": "Any pipeline, by its key.",
  "formRules.AT_LEAST_ONE_TRUE": "At least one of these yes-or-no questions must be answered yes — for example, a grant, a loan, or both.",
  "formRules.DIFFERENT_VALUES": "These answers must all differ — for example, a first and a second choice of bank.",
  "formRules.SUM_AT_MOST": "These amounts together may not exceed a fixed limit.",
  "formRules.AT_MOST_FIELD": "The first answer may not exceed the second — for example, a loan asked for may not exceed the project's cost.",
  "eligibilityRules.PRIOR_APPLICATION_HAS_FLAG": "The enterprise has an earlier application that holds a status flag, held for at least a number of months.",
  "eligibilityRules.PRIOR_RECORDED_VALUE_AT_LEAST": "An earlier application of the enterprise recorded a value of at least an amount.",
  "eligibilityRules.NO_OPEN_APPLICATION_OF_KIND": "The enterprise has no unfinished application of a kind — a draft, or one still being worked.",
  "eligibilityRules.MAX_APPLICATIONS_OF_KIND": "The enterprise has made fewer than a number of applications of a kind, across every cycle.",
  "eligibilityRules.ENTERPRISE_AGE_AT_LEAST": "The enterprise was established at least a number of months ago.",
  "effects.ADD_STATUS": "Adds a status flag. A flag that ends the pipeline is added by COMPLETE_PIPELINE or CLOSE_APPLICATION instead.",
  "effects.REMOVE_STATUS": "Removes a status flag.",
  "effects.SET_RECORDED_VALUE": "Keeps what the officer entered as a named value on the application, such as the approved grant.",
  "effects.REQUEST_REVISION": "Asks the applicant to correct the form stages the officer names. When they resubmit, the application returns to this stage.",
  "effects.NOTIFY_APPLICANT": "Tells the applicant, on their timeline and by email when asked to.",
  "effects.ADD_INTERNAL_NOTE": "Keeps what the officer wrote as a staff-only note on the application.",
  "effects.MOVE_TO_STAGE": "Sends the application to another stage.",
  "effects.MOVE_BY_CHOICE": "Sends the application to the stage chosen by one of the action's inputs — for example, the bank.",
  "effects.RETURN_TO_PREVIOUS": "Sends the application back to the stage it actually came from.",
  "effects.COMPLETE_PIPELINE": "Finishes the application's journey successfully, with a flag that ends the pipeline.",
  "effects.CLOSE_APPLICATION": "Ends the application's journey without success, such as a rejection, with a flag that ends the pipeline."
}
