-- 0003 · Configurable pipelines
--
-- Replaces the hard-coded workflow — desk review, partner bank, programme
-- decision, award, disbursement, assessment and recovery — with configurable
-- pipelines: an application is submitted into the pipeline version its cycle
-- pinned, sits at a configured stage, holds configured status flags, and is
-- moved by configured stage actions. A cycle declares the kinds of application
-- it accepts, each with eligibility rules, and its form may declare rules
-- about several answers at once.
--
-- There is no backward compatibility. Production holds only QA data, so the
-- old workflow's tables and columns are dropped rather than kept dormant, and
-- every application and programme cycle is removed (step 2) — an application
-- cannot be carried into a pipeline that did not exist when it was worked.
--
-- Three properties this file must keep, and why:
--
-- * Destructive steps are named. Each table, column and constraint removed is
--   listed below by name, in dependency order, so review reads what is lost.
--
-- * Idempotent. Every statement checks before it acts — `IF EXISTS`,
--   `IF NOT EXISTS`, constraints guarded by `pg_constraint` — and the data
--   removal is guarded by a column this file drops, so a second run changes
--   nothing. `check:migration` runs it twice and compares.
--
-- * Durable. drizzle applies pending migrations inside one transaction, so the
--   file lands whole or not at all, and nothing here is a trigger.
--
-- Generated by `drizzle-kit generate` from the Drizzle schema, then hardened
-- by hand. Names match `src/db/schema` and the 0003 snapshot exactly;
-- `npm run db:schema:check` and `check:migration` hold them to that.

-- 1. The old workflow's tables ------------------------------------------------

-- Every table only the removed desk-review, bank, decision, award, disbursement,
-- assessment, recovery, qualifying-award and assignment code wrote, found by
-- following foreign keys from the application and the cycle. Dropped first so
-- nothing below has to step around their foreign keys. CASCADE removes only
-- those keys — every table they pointed from is kept and emptied in step 2.
DROP TABLE IF EXISTS "seb_partner_bank_outcome" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_partner_bank_referral" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_partner_bank_referral_version" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_programme_decision" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_application_qualifying_award" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_application_qualifying_award_version" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_award_assessment" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_disbursement" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_funding_award" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_funding_award_version" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_utilization_obligation" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_programme_cycle_assessment_rule" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_programme_cycle_identifier_rule" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_programme_cycle_reason" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_recovery_case" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_recovery_case_version" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_recovery_entry" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_application_assignment_event" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_desk_review" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_desk_review_check" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "seb_desk_review_identifier" CASCADE;
--> statement-breakpoint

-- 2. The QA data --------------------------------------------------------------

-- Every application and every programme cycle, with everything hanging off
-- either: versions, answers, submissions, documents, scans, upload intents,
-- events, revision requests, notes, form templates and policy documents.
-- Users, roles, grants, enterprises and their funding cases, announcements and
-- the activity history are kept. The history names applications by id only
-- (no foreign key), so its rows stay readable as recorded.
--
-- Guarded by the legacy `application_type` column, which step 5 drops: the
-- first run empties these tables, and any later run — once real applications
-- exist in the new shape — changes nothing. One TRUNCATE, because the heads
-- and their versions reference each other and no single DELETE order exists.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = 'seb_application'
       AND column_name = 'application_type'
  ) THEN
    TRUNCATE TABLE
      "seb_application_event",
      "seb_revision_request",
      "seb_application_internal_note",
      "seb_application_submission_document",
      "seb_application_submission",
      "seb_application_document_scan",
      "seb_application_document_version",
      "seb_application_document",
      "seb_document_upload_intent",
      "seb_application_version_answer",
      "seb_application_version",
      "seb_application",
      "seb_cycle_policy_document_scan",
      "seb_cycle_policy_document_version",
      "seb_cycle_policy_upload_intent",
      "seb_cycle_policy_document",
      "seb_programme_cycle_event",
      "seb_programme_cycle_form_field_condition",
      "seb_programme_cycle_form_field_option",
      "seb_programme_cycle_form_field",
      "seb_programme_cycle_form_group_definition_member_option",
      "seb_programme_cycle_form_group_definition_member",
      "seb_programme_cycle_form_group_definition",
      "seb_programme_cycle_form_stage",
      "seb_programme_cycle_version",
      "seb_programme_cycle";
  END IF;
END $$;
--> statement-breakpoint
-- Grants of permissions the catalogue no longer has. A role that held one
-- keeps every other permission it held; the pairs removed are the whole of
-- `decision`, `funding` and `recovery`, and `application` `review` and
-- `refer`. A no-op once they are gone, because nothing can write them again.
DELETE FROM "core_role_permission"
 WHERE "resource" IN ('decision', 'funding', 'recovery')
    OR ("resource" = 'application' AND "action" IN ('review', 'refer'));
--> statement-breakpoint

-- 3. The old constraints and index --------------------------------------------

-- Dropped by name before the columns they read. The status, phase, role,
-- months and event-status checks are re-added in step 8 with their new
-- definitions under the same names.
ALTER TABLE "seb_application" DROP CONSTRAINT IF EXISTS "seb_application_assignment_version_check";
--> statement-breakpoint
ALTER TABLE "seb_application" DROP CONSTRAINT IF EXISTS "seb_application_assignment_group_check";
--> statement-breakpoint
ALTER TABLE "seb_application" DROP CONSTRAINT IF EXISTS "seb_application_type_check";
--> statement-breakpoint
ALTER TABLE "seb_application" DROP CONSTRAINT IF EXISTS "seb_application_status_check";
--> statement-breakpoint
ALTER TABLE "seb_application" DROP CONSTRAINT IF EXISTS "seb_application_phase_check";
--> statement-breakpoint
ALTER TABLE "seb_application_version" DROP CONSTRAINT IF EXISTS "seb_application_version_type_check";
--> statement-breakpoint
ALTER TABLE "seb_application_version" DROP CONSTRAINT IF EXISTS "seb_application_version_prior_award_check";
--> statement-breakpoint
ALTER TABLE "seb_application_version" DROP CONSTRAINT IF EXISTS "seb_application_version_phase_check";
--> statement-breakpoint
ALTER TABLE "seb_programme_cycle_form_field" DROP CONSTRAINT IF EXISTS "seb_programme_cycle_form_field_role_check";
--> statement-breakpoint
ALTER TABLE "seb_programme_cycle_version" DROP CONSTRAINT IF EXISTS "seb_programme_cycle_version_months_check";
--> statement-breakpoint
ALTER TABLE "seb_application_event" DROP CONSTRAINT IF EXISTS "seb_application_event_from_status_check";
--> statement-breakpoint
ALTER TABLE "seb_application_event" DROP CONSTRAINT IF EXISTS "seb_application_event_to_status_check";
--> statement-breakpoint
ALTER TABLE "seb_application" DROP CONSTRAINT IF EXISTS "seb_application_assigned_to_user_id_core_user_id_fk";
--> statement-breakpoint
ALTER TABLE "seb_revision_request" DROP CONSTRAINT IF EXISTS "seb_revision_request_reason_category_id_seb_programme_cycle_reason_id_fk";
--> statement-breakpoint
DROP INDEX IF EXISTS "seb_application_assignment_idx";
--> statement-breakpoint

-- 4. The new tables -----------------------------------------------------------

-- Pipelines, their versions and stages, stage ownership, the stage-action
-- history, cycle application kinds with their eligibility rules, and a form's
-- cross-field rules. Each carries its own single-row checks; the foreign keys
-- between them follow in step 6, once every table exists.
CREATE TABLE IF NOT EXISTS "seb_programme_cycle_form_rule" (
	"id" text PRIMARY KEY NOT NULL,
	"programme_cycle_id" text NOT NULL,
	"programme_cycle_version" integer NOT NULL,
	"rule_key" text NOT NULL,
	"rule_type" text NOT NULL,
	"stage_key" text NOT NULL,
	"message" text NOT NULL,
	"limit_value" bigint,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "seb_programme_cycle_form_rule_key_uq" UNIQUE("programme_cycle_id","programme_cycle_version","rule_key"),
	CONSTRAINT "seb_programme_cycle_form_rule_key_check" CHECK ("seb_programme_cycle_form_rule"."rule_key" ~ '^[A-Z][A-Z0-9_]{1,63}$'),
	CONSTRAINT "seb_programme_cycle_form_rule_type_check" CHECK ("seb_programme_cycle_form_rule"."rule_type" IN ('AT_LEAST_ONE_TRUE', 'DIFFERENT_VALUES', 'SUM_AT_MOST', 'AT_MOST_FIELD')),
	CONSTRAINT "seb_programme_cycle_form_rule_message_check" CHECK (char_length("seb_programme_cycle_form_rule"."message") BETWEEN 1 AND 300),
	CONSTRAINT "seb_programme_cycle_form_rule_limit_check" CHECK (("seb_programme_cycle_form_rule"."rule_type" = 'SUM_AT_MOST' AND "seb_programme_cycle_form_rule"."limit_value" IS NOT NULL AND "seb_programme_cycle_form_rule"."limit_value" >= 0)
        OR ("seb_programme_cycle_form_rule"."rule_type" <> 'SUM_AT_MOST' AND "seb_programme_cycle_form_rule"."limit_value" IS NULL))
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "seb_programme_cycle_form_rule_operand" (
	"id" text PRIMARY KEY NOT NULL,
	"programme_cycle_id" text NOT NULL,
	"programme_cycle_version" integer NOT NULL,
	"rule_key" text NOT NULL,
	"position" integer NOT NULL,
	"field_key" text NOT NULL,
	"field_type" text NOT NULL,
	CONSTRAINT "seb_programme_cycle_form_rule_operand_position_check" CHECK ("seb_programme_cycle_form_rule_operand"."position" >= 1)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "seb_application_stage_action" (
	"id" text PRIMARY KEY NOT NULL,
	"application_id" text NOT NULL,
	"pipeline_id" text NOT NULL,
	"pipeline_version" integer NOT NULL,
	"stage_key" text NOT NULL,
	"action_key" text NOT NULL,
	"actor_user_id" text NOT NULL,
	"status_version" integer NOT NULL,
	"to_stage_key" text,
	"inputs" jsonb NOT NULL,
	"flags_added" text[] NOT NULL,
	"flags_removed" text[] NOT NULL,
	"recorded" jsonb NOT NULL,
	"revision_stage_keys" text[] NOT NULL,
	"self_review_disclosed" boolean NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "seb_application_stage_action_version_uq" UNIQUE("application_id","status_version"),
	CONSTRAINT "seb_application_stage_action_application_uq" UNIQUE("application_id","id"),
	CONSTRAINT "seb_application_stage_action_version_check" CHECK ("seb_application_stage_action"."status_version" >= 2),
	CONSTRAINT "seb_application_stage_action_json_check" CHECK (jsonb_typeof("seb_application_stage_action"."inputs") = 'object' AND jsonb_typeof("seb_application_stage_action"."recorded") = 'object'
        AND octet_length("seb_application_stage_action"."inputs"::text) <= 65536)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "seb_pipeline" (
	"id" text PRIMARY KEY NOT NULL,
	"key" text NOT NULL,
	"name" text NOT NULL,
	"description" text NOT NULL,
	"current_published_version" integer,
	"created_at" timestamp with time zone NOT NULL,
	"created_by_user_id" text NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"retired_at" timestamp with time zone,
	"retired_by_user_id" text,
	"retire_reason" text,
	CONSTRAINT "seb_pipeline_key_uq" UNIQUE("key"),
	CONSTRAINT "seb_pipeline_key_check" CHECK ("seb_pipeline"."key" ~ '^[A-Z][A-Z0-9_]{1,63}$'),
	CONSTRAINT "seb_pipeline_name_check" CHECK (char_length("seb_pipeline"."name") BETWEEN 1 AND 120),
	CONSTRAINT "seb_pipeline_description_check" CHECK (char_length("seb_pipeline"."description") <= 1000),
	CONSTRAINT "seb_pipeline_published_version_check" CHECK ("seb_pipeline"."current_published_version" IS NULL OR "seb_pipeline"."current_published_version" >= 1),
	CONSTRAINT "seb_pipeline_retire_group_check" CHECK (("seb_pipeline"."retired_at" IS NULL AND "seb_pipeline"."retired_by_user_id" IS NULL AND "seb_pipeline"."retire_reason" IS NULL)
        OR ("seb_pipeline"."retired_at" IS NOT NULL AND "seb_pipeline"."retired_by_user_id" IS NOT NULL AND "seb_pipeline"."retire_reason" IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "seb_pipeline_stage" (
	"pipeline_id" text NOT NULL,
	"stage_key" text NOT NULL,
	"owners_version" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "seb_pipeline_stage_pk" PRIMARY KEY("pipeline_id","stage_key"),
	CONSTRAINT "seb_pipeline_stage_key_check" CHECK ("seb_pipeline_stage"."stage_key" ~ '^[A-Z][A-Z0-9_]{1,63}$'),
	CONSTRAINT "seb_pipeline_stage_owners_version_check" CHECK ("seb_pipeline_stage"."owners_version" >= 0)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "seb_pipeline_stage_owner" (
	"id" text PRIMARY KEY NOT NULL,
	"pipeline_id" text NOT NULL,
	"stage_key" text NOT NULL,
	"role_id" text NOT NULL,
	"added_at" timestamp with time zone NOT NULL,
	"added_by_user_id" text NOT NULL,
	"removed_at" timestamp with time zone,
	"removed_by_user_id" text,
	"removal_reason" text,
	CONSTRAINT "seb_pipeline_stage_owner_removal_check" CHECK (("seb_pipeline_stage_owner"."removed_at" IS NULL AND "seb_pipeline_stage_owner"."removed_by_user_id" IS NULL AND "seb_pipeline_stage_owner"."removal_reason" IS NULL)
        OR ("seb_pipeline_stage_owner"."removed_at" IS NOT NULL AND "seb_pipeline_stage_owner"."removed_by_user_id" IS NOT NULL AND "seb_pipeline_stage_owner"."removal_reason" IS NOT NULL
            AND "seb_pipeline_stage_owner"."removed_at" >= "seb_pipeline_stage_owner"."added_at"))
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "seb_pipeline_version" (
	"id" text PRIMARY KEY NOT NULL,
	"pipeline_id" text NOT NULL,
	"version" integer NOT NULL,
	"status" text NOT NULL,
	"definition" jsonb NOT NULL,
	"definition_schema" smallint DEFAULT 1 NOT NULL,
	"revision" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"created_by_user_id" text NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"published_at" timestamp with time zone,
	"published_by_user_id" text,
	"change_note" text,
	CONSTRAINT "seb_pipeline_version_uq" UNIQUE("pipeline_id","version"),
	CONSTRAINT "seb_pipeline_version_version_check" CHECK ("seb_pipeline_version"."version" >= 1),
	CONSTRAINT "seb_pipeline_version_revision_check" CHECK ("seb_pipeline_version"."revision" >= 1),
	CONSTRAINT "seb_pipeline_version_status_check" CHECK ("seb_pipeline_version"."status" IN ('DRAFT', 'PUBLISHED')),
	CONSTRAINT "seb_pipeline_version_schema_check" CHECK ("seb_pipeline_version"."definition_schema" = 1),
	CONSTRAINT "seb_pipeline_version_definition_check" CHECK (jsonb_typeof("seb_pipeline_version"."definition") = 'object' AND octet_length("seb_pipeline_version"."definition"::text) <= 262144),
	CONSTRAINT "seb_pipeline_version_note_check" CHECK ("seb_pipeline_version"."change_note" IS NULL OR char_length("seb_pipeline_version"."change_note") <= 500),
	CONSTRAINT "seb_pipeline_version_publish_group_check" CHECK (("seb_pipeline_version"."status" = 'DRAFT' AND "seb_pipeline_version"."published_at" IS NULL AND "seb_pipeline_version"."published_by_user_id" IS NULL)
        OR ("seb_pipeline_version"."status" = 'PUBLISHED' AND "seb_pipeline_version"."published_at" IS NOT NULL AND "seb_pipeline_version"."published_by_user_id" IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "seb_pipeline_version_stage" (
	"pipeline_id" text NOT NULL,
	"version" integer NOT NULL,
	"stage_key" text NOT NULL,
	"position" integer NOT NULL,
	"is_initial" boolean NOT NULL,
	CONSTRAINT "seb_pipeline_version_stage_pk" PRIMARY KEY("pipeline_id","version","stage_key"),
	CONSTRAINT "seb_pipeline_version_stage_position_check" CHECK ("seb_pipeline_version_stage"."position" >= 0)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "seb_programme_cycle_application_kind" (
	"id" text PRIMARY KEY NOT NULL,
	"programme_cycle_id" text NOT NULL,
	"programme_cycle_version" integer NOT NULL,
	"kind_key" text NOT NULL,
	"label" text NOT NULL,
	"description" text,
	"sort_order" integer NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "seb_programme_cycle_application_kind_key_uq" UNIQUE("programme_cycle_id","programme_cycle_version","kind_key"),
	CONSTRAINT "seb_programme_cycle_application_kind_key_check" CHECK ("seb_programme_cycle_application_kind"."kind_key" ~ '^[A-Z][A-Z0-9_]{1,63}$'),
	CONSTRAINT "seb_programme_cycle_application_kind_label_check" CHECK (char_length("seb_programme_cycle_application_kind"."label") BETWEEN 1 AND 80
        AND ("seb_programme_cycle_application_kind"."description" IS NULL OR char_length("seb_programme_cycle_application_kind"."description") <= 500)),
	CONSTRAINT "seb_programme_cycle_application_kind_order_check" CHECK ("seb_programme_cycle_application_kind"."sort_order" >= 1)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "seb_programme_cycle_application_kind_rule" (
	"id" text PRIMARY KEY NOT NULL,
	"programme_cycle_id" text NOT NULL,
	"programme_cycle_version" integer NOT NULL,
	"kind_key" text NOT NULL,
	"position" integer NOT NULL,
	"rule_type" text NOT NULL,
	"params" jsonb NOT NULL,
	CONSTRAINT "seb_programme_cycle_application_kind_rule_position_check" CHECK ("seb_programme_cycle_application_kind_rule"."position" >= 1),
	CONSTRAINT "seb_programme_cycle_application_kind_rule_type_check" CHECK ("seb_programme_cycle_application_kind_rule"."rule_type" IN ('PRIOR_APPLICATION_HAS_FLAG', 'PRIOR_RECORDED_VALUE_AT_LEAST', 'NO_OPEN_APPLICATION_OF_KIND', 'MAX_APPLICATIONS_OF_KIND', 'ENTERPRISE_AGE_AT_LEAST')),
	CONSTRAINT "seb_programme_cycle_application_kind_rule_params_check" CHECK (jsonb_typeof("seb_programme_cycle_application_kind_rule"."params") = 'object' AND octet_length("seb_programme_cycle_application_kind_rule"."params"::text) <= 4096)
);
--> statement-breakpoint

-- 5. Columns ------------------------------------------------------------------

-- Added NOT NULL without a default where the value has no honest default: the
-- tables they land on were emptied in step 2, so no existing row needs one.
-- Then the old workflow's columns go.
ALTER TABLE "seb_application" ADD COLUMN IF NOT EXISTS "application_kind" text NOT NULL;
--> statement-breakpoint
ALTER TABLE "seb_application" ADD COLUMN IF NOT EXISTS "pipeline_id" text NOT NULL;
--> statement-breakpoint
ALTER TABLE "seb_application" ADD COLUMN IF NOT EXISTS "pipeline_version" integer NOT NULL;
--> statement-breakpoint
ALTER TABLE "seb_application" ADD COLUMN IF NOT EXISTS "current_stage_key" text;
--> statement-breakpoint
ALTER TABLE "seb_application" ADD COLUMN IF NOT EXISTS "stage_entered_at" timestamp with time zone;
--> statement-breakpoint
ALTER TABLE "seb_application" ADD COLUMN IF NOT EXISTS "stage_trail" text[] DEFAULT '{}'::text[] NOT NULL;
--> statement-breakpoint
ALTER TABLE "seb_application" ADD COLUMN IF NOT EXISTS "status_flags" text[] DEFAULT '{}'::text[] NOT NULL;
--> statement-breakpoint
ALTER TABLE "seb_application" ADD COLUMN IF NOT EXISTS "recorded_values" jsonb DEFAULT '{}'::jsonb NOT NULL;
--> statement-breakpoint
ALTER TABLE "seb_application_version" ADD COLUMN IF NOT EXISTS "application_kind" text NOT NULL;
--> statement-breakpoint
ALTER TABLE "seb_programme_cycle_version" ADD COLUMN IF NOT EXISTS "pipeline_id" text NOT NULL;
--> statement-breakpoint
ALTER TABLE "seb_programme_cycle_version" ADD COLUMN IF NOT EXISTS "pipeline_version" integer;
--> statement-breakpoint
ALTER TABLE "seb_application_event" ADD COLUMN IF NOT EXISTS "stage_action_id" text;
--> statement-breakpoint
ALTER TABLE "seb_application" DROP COLUMN IF EXISTS "application_type";
--> statement-breakpoint
ALTER TABLE "seb_application" DROP COLUMN IF EXISTS "assigned_to_user_id";
--> statement-breakpoint
ALTER TABLE "seb_application" DROP COLUMN IF EXISTS "assigned_at";
--> statement-breakpoint
ALTER TABLE "seb_application" DROP COLUMN IF EXISTS "assignment_version";
--> statement-breakpoint
ALTER TABLE "seb_application_version" DROP COLUMN IF EXISTS "application_type";
--> statement-breakpoint
ALTER TABLE "seb_application_version" DROP COLUMN IF EXISTS "prior_sanction_order_number";
--> statement-breakpoint
ALTER TABLE "seb_application_version" DROP COLUMN IF EXISTS "prior_sanction_date";
--> statement-breakpoint
ALTER TABLE "seb_application_version" DROP COLUMN IF EXISTS "prior_net_disbursed_amount_paise";
--> statement-breakpoint
ALTER TABLE "seb_application_version" DROP COLUMN IF EXISTS "continuous_operation_months";
--> statement-breakpoint
ALTER TABLE "seb_programme_cycle" DROP COLUMN IF EXISTS "partner_bank_guidance";
--> statement-breakpoint
ALTER TABLE "seb_programme_cycle_version" DROP COLUMN IF EXISTS "partner_bank_guidance";
--> statement-breakpoint
ALTER TABLE "seb_programme_cycle_version" DROP COLUMN IF EXISTS "expansion_wait_months";
--> statement-breakpoint
ALTER TABLE "seb_revision_request" DROP COLUMN IF EXISTS "reason_category_id";
--> statement-breakpoint

-- 6. Foreign keys -------------------------------------------------------------

-- Postgres has no `ADD CONSTRAINT IF NOT EXISTS`, so each is added only when
-- its name is not already on its table.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_programme_cycle_form_rule_stage_fk' AND conrelid = '"seb_programme_cycle_form_rule"'::regclass
  ) THEN
    ALTER TABLE "seb_programme_cycle_form_rule" ADD CONSTRAINT "seb_programme_cycle_form_rule_stage_fk"
      FOREIGN KEY ("programme_cycle_id","programme_cycle_version","stage_key") REFERENCES "public"."seb_programme_cycle_form_stage"("programme_cycle_id","programme_cycle_version","stage_key") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_programme_cycle_form_rule_operand_rule_fk' AND conrelid = '"seb_programme_cycle_form_rule_operand"'::regclass
  ) THEN
    ALTER TABLE "seb_programme_cycle_form_rule_operand" ADD CONSTRAINT "seb_programme_cycle_form_rule_operand_rule_fk"
      FOREIGN KEY ("programme_cycle_id","programme_cycle_version","rule_key") REFERENCES "public"."seb_programme_cycle_form_rule"("programme_cycle_id","programme_cycle_version","rule_key") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_programme_cycle_form_rule_operand_field_fk' AND conrelid = '"seb_programme_cycle_form_rule_operand"'::regclass
  ) THEN
    ALTER TABLE "seb_programme_cycle_form_rule_operand" ADD CONSTRAINT "seb_programme_cycle_form_rule_operand_field_fk"
      FOREIGN KEY ("programme_cycle_id","programme_cycle_version","field_key","field_type") REFERENCES "public"."seb_programme_cycle_form_field"("programme_cycle_id","programme_cycle_version","field_key","field_type") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_stage_action_application_id_seb_application_id_fk' AND conrelid = '"seb_application_stage_action"'::regclass
  ) THEN
    ALTER TABLE "seb_application_stage_action" ADD CONSTRAINT "seb_application_stage_action_application_id_seb_application_id_fk"
      FOREIGN KEY ("application_id") REFERENCES "public"."seb_application"("id") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_stage_action_actor_user_id_core_user_id_fk' AND conrelid = '"seb_application_stage_action"'::regclass
  ) THEN
    ALTER TABLE "seb_application_stage_action" ADD CONSTRAINT "seb_application_stage_action_actor_user_id_core_user_id_fk"
      FOREIGN KEY ("actor_user_id") REFERENCES "public"."core_user"("id") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_stage_action_stage_fk' AND conrelid = '"seb_application_stage_action"'::regclass
  ) THEN
    ALTER TABLE "seb_application_stage_action" ADD CONSTRAINT "seb_application_stage_action_stage_fk"
      FOREIGN KEY ("pipeline_id","pipeline_version","stage_key") REFERENCES "public"."seb_pipeline_version_stage"("pipeline_id","version","stage_key") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_stage_action_to_stage_fk' AND conrelid = '"seb_application_stage_action"'::regclass
  ) THEN
    ALTER TABLE "seb_application_stage_action" ADD CONSTRAINT "seb_application_stage_action_to_stage_fk"
      FOREIGN KEY ("pipeline_id","pipeline_version","to_stage_key") REFERENCES "public"."seb_pipeline_version_stage"("pipeline_id","version","stage_key") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_pipeline_created_by_user_id_core_user_id_fk' AND conrelid = '"seb_pipeline"'::regclass
  ) THEN
    ALTER TABLE "seb_pipeline" ADD CONSTRAINT "seb_pipeline_created_by_user_id_core_user_id_fk"
      FOREIGN KEY ("created_by_user_id") REFERENCES "public"."core_user"("id") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_pipeline_retired_by_user_id_core_user_id_fk' AND conrelid = '"seb_pipeline"'::regclass
  ) THEN
    ALTER TABLE "seb_pipeline" ADD CONSTRAINT "seb_pipeline_retired_by_user_id_core_user_id_fk"
      FOREIGN KEY ("retired_by_user_id") REFERENCES "public"."core_user"("id") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_pipeline_stage_pipeline_id_seb_pipeline_id_fk' AND conrelid = '"seb_pipeline_stage"'::regclass
  ) THEN
    ALTER TABLE "seb_pipeline_stage" ADD CONSTRAINT "seb_pipeline_stage_pipeline_id_seb_pipeline_id_fk"
      FOREIGN KEY ("pipeline_id") REFERENCES "public"."seb_pipeline"("id") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_pipeline_stage_owner_role_id_core_role_id_fk' AND conrelid = '"seb_pipeline_stage_owner"'::regclass
  ) THEN
    ALTER TABLE "seb_pipeline_stage_owner" ADD CONSTRAINT "seb_pipeline_stage_owner_role_id_core_role_id_fk"
      FOREIGN KEY ("role_id") REFERENCES "public"."core_role"("id") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_pipeline_stage_owner_added_by_user_id_core_user_id_fk' AND conrelid = '"seb_pipeline_stage_owner"'::regclass
  ) THEN
    ALTER TABLE "seb_pipeline_stage_owner" ADD CONSTRAINT "seb_pipeline_stage_owner_added_by_user_id_core_user_id_fk"
      FOREIGN KEY ("added_by_user_id") REFERENCES "public"."core_user"("id") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_pipeline_stage_owner_removed_by_user_id_core_user_id_fk' AND conrelid = '"seb_pipeline_stage_owner"'::regclass
  ) THEN
    ALTER TABLE "seb_pipeline_stage_owner" ADD CONSTRAINT "seb_pipeline_stage_owner_removed_by_user_id_core_user_id_fk"
      FOREIGN KEY ("removed_by_user_id") REFERENCES "public"."core_user"("id") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_pipeline_stage_owner_stage_fk' AND conrelid = '"seb_pipeline_stage_owner"'::regclass
  ) THEN
    ALTER TABLE "seb_pipeline_stage_owner" ADD CONSTRAINT "seb_pipeline_stage_owner_stage_fk"
      FOREIGN KEY ("pipeline_id","stage_key") REFERENCES "public"."seb_pipeline_stage"("pipeline_id","stage_key") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_pipeline_version_pipeline_id_seb_pipeline_id_fk' AND conrelid = '"seb_pipeline_version"'::regclass
  ) THEN
    ALTER TABLE "seb_pipeline_version" ADD CONSTRAINT "seb_pipeline_version_pipeline_id_seb_pipeline_id_fk"
      FOREIGN KEY ("pipeline_id") REFERENCES "public"."seb_pipeline"("id") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_pipeline_version_created_by_user_id_core_user_id_fk' AND conrelid = '"seb_pipeline_version"'::regclass
  ) THEN
    ALTER TABLE "seb_pipeline_version" ADD CONSTRAINT "seb_pipeline_version_created_by_user_id_core_user_id_fk"
      FOREIGN KEY ("created_by_user_id") REFERENCES "public"."core_user"("id") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_pipeline_version_published_by_user_id_core_user_id_fk' AND conrelid = '"seb_pipeline_version"'::regclass
  ) THEN
    ALTER TABLE "seb_pipeline_version" ADD CONSTRAINT "seb_pipeline_version_published_by_user_id_core_user_id_fk"
      FOREIGN KEY ("published_by_user_id") REFERENCES "public"."core_user"("id") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_pipeline_version_stage_version_fk' AND conrelid = '"seb_pipeline_version_stage"'::regclass
  ) THEN
    ALTER TABLE "seb_pipeline_version_stage" ADD CONSTRAINT "seb_pipeline_version_stage_version_fk"
      FOREIGN KEY ("pipeline_id","version") REFERENCES "public"."seb_pipeline_version"("pipeline_id","version") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_pipeline_version_stage_stage_fk' AND conrelid = '"seb_pipeline_version_stage"'::regclass
  ) THEN
    ALTER TABLE "seb_pipeline_version_stage" ADD CONSTRAINT "seb_pipeline_version_stage_stage_fk"
      FOREIGN KEY ("pipeline_id","stage_key") REFERENCES "public"."seb_pipeline_stage"("pipeline_id","stage_key") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_programme_cycle_application_kind_version_fk' AND conrelid = '"seb_programme_cycle_application_kind"'::regclass
  ) THEN
    ALTER TABLE "seb_programme_cycle_application_kind" ADD CONSTRAINT "seb_programme_cycle_application_kind_version_fk"
      FOREIGN KEY ("programme_cycle_id","programme_cycle_version") REFERENCES "public"."seb_programme_cycle_version"("programme_cycle_id","version") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_programme_cycle_application_kind_rule_kind_fk' AND conrelid = '"seb_programme_cycle_application_kind_rule"'::regclass
  ) THEN
    ALTER TABLE "seb_programme_cycle_application_kind_rule" ADD CONSTRAINT "seb_programme_cycle_application_kind_rule_kind_fk"
      FOREIGN KEY ("programme_cycle_id","programme_cycle_version","kind_key") REFERENCES "public"."seb_programme_cycle_application_kind"("programme_cycle_id","programme_cycle_version","kind_key") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_pipeline_version_fk' AND conrelid = '"seb_application"'::regclass
  ) THEN
    ALTER TABLE "seb_application" ADD CONSTRAINT "seb_application_pipeline_version_fk"
      FOREIGN KEY ("pipeline_id","pipeline_version") REFERENCES "public"."seb_pipeline_version"("pipeline_id","version") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_current_stage_fk' AND conrelid = '"seb_application"'::regclass
  ) THEN
    ALTER TABLE "seb_application" ADD CONSTRAINT "seb_application_current_stage_fk"
      FOREIGN KEY ("pipeline_id","pipeline_version","current_stage_key") REFERENCES "public"."seb_pipeline_version_stage"("pipeline_id","version","stage_key") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_programme_cycle_version_pipeline_id_seb_pipeline_id_fk' AND conrelid = '"seb_programme_cycle_version"'::regclass
  ) THEN
    ALTER TABLE "seb_programme_cycle_version" ADD CONSTRAINT "seb_programme_cycle_version_pipeline_id_seb_pipeline_id_fk"
      FOREIGN KEY ("pipeline_id") REFERENCES "public"."seb_pipeline"("id") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_programme_cycle_version_pipeline_version_fk' AND conrelid = '"seb_programme_cycle_version"'::regclass
  ) THEN
    ALTER TABLE "seb_programme_cycle_version" ADD CONSTRAINT "seb_programme_cycle_version_pipeline_version_fk"
      FOREIGN KEY ("pipeline_id","pipeline_version") REFERENCES "public"."seb_pipeline_version"("pipeline_id","version") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_event_stage_action_fk' AND conrelid = '"seb_application_event"'::regclass
  ) THEN
    ALTER TABLE "seb_application_event" ADD CONSTRAINT "seb_application_event_stage_action_fk"
      FOREIGN KEY ("application_id","stage_action_id") REFERENCES "public"."seb_application_stage_action"("application_id","id") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint

-- 7. Indexes ------------------------------------------------------------------

-- The stage queue (pipeline, stage, time entered), the status-flag GIN index,
-- the per-pipeline status index, and the uniqueness the new tables rely on.
CREATE UNIQUE INDEX IF NOT EXISTS "seb_programme_cycle_form_rule_operand_position_uq" ON "seb_programme_cycle_form_rule_operand" USING btree ("programme_cycle_id","programme_cycle_version","rule_key","position");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "seb_programme_cycle_form_rule_operand_field_uq" ON "seb_programme_cycle_form_rule_operand" USING btree ("programme_cycle_id","programme_cycle_version","rule_key","field_key");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "seb_application_stage_action_history_idx" ON "seb_application_stage_action" USING btree ("application_id","created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "seb_application_stage_action_actor_idx" ON "seb_application_stage_action" USING btree ("actor_user_id","application_id");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "seb_pipeline_stage_owner_live_uq" ON "seb_pipeline_stage_owner" USING btree ("pipeline_id","stage_key","role_id") WHERE "seb_pipeline_stage_owner"."removed_at" IS NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "seb_pipeline_stage_owner_role_idx" ON "seb_pipeline_stage_owner" USING btree ("role_id") WHERE "seb_pipeline_stage_owner"."removed_at" IS NULL;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "seb_pipeline_version_one_draft_uq" ON "seb_pipeline_version" USING btree ("pipeline_id") WHERE "seb_pipeline_version"."status" = 'DRAFT';
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "seb_pipeline_version_stage_initial_uq" ON "seb_pipeline_version_stage" USING btree ("pipeline_id","version") WHERE "seb_pipeline_version_stage"."is_initial";
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "seb_programme_cycle_application_kind_order_uq" ON "seb_programme_cycle_application_kind" USING btree ("programme_cycle_id","programme_cycle_version","sort_order");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "seb_programme_cycle_application_kind_rule_position_uq" ON "seb_programme_cycle_application_kind_rule" USING btree ("programme_cycle_id","programme_cycle_version","kind_key","position");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "seb_application_stage_queue_idx" ON "seb_application" USING btree ("pipeline_id","current_stage_key","stage_entered_at","id") WHERE "seb_application"."deleted_at" IS NULL AND "seb_application"."current_stage_key" IS NOT NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "seb_application_status_flags_idx" ON "seb_application" USING gin ("status_flags") WHERE "seb_application"."deleted_at" IS NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "seb_application_pipeline_status_idx" ON "seb_application" USING btree ("pipeline_id","status","status_changed_at") WHERE "seb_application"."deleted_at" IS NULL;
--> statement-breakpoint

-- 8. Checks -------------------------------------------------------------------

-- The new rows' shapes, and the replaced checks: statuses are DRAFT and
-- IN_PIPELINE only, phase stays positive, a role binding is optional but
-- pinned, and a cycle version outside DRAFT always names its pipeline version.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_kind_check' AND conrelid = '"seb_application"'::regclass
  ) THEN
    ALTER TABLE "seb_application" ADD CONSTRAINT "seb_application_kind_check"
      CHECK ("seb_application"."application_kind" ~ '^[A-Z][A-Z0-9_]{1,63}$');
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_stage_lifecycle_check' AND conrelid = '"seb_application"'::regclass
  ) THEN
    ALTER TABLE "seb_application" ADD CONSTRAINT "seb_application_stage_lifecycle_check"
      CHECK (("seb_application"."status" = 'DRAFT' AND "seb_application"."current_stage_key" IS NULL AND "seb_application"."stage_entered_at" IS NULL)
        OR ("seb_application"."status" = 'IN_PIPELINE' AND "seb_application"."current_stage_key" IS NOT NULL AND "seb_application"."stage_entered_at" IS NOT NULL)
        OR ("seb_application"."status" = 'IN_PIPELINE' AND "seb_application"."current_stage_key" IS NULL AND "seb_application"."stage_entered_at" IS NULL));
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_status_flags_check' AND conrelid = '"seb_application"'::regclass
  ) THEN
    ALTER TABLE "seb_application" ADD CONSTRAINT "seb_application_status_flags_check"
      CHECK (cardinality("seb_application"."status_flags") <= 32
        AND array_position("seb_application"."status_flags", NULL) IS NULL
        AND array_to_string("seb_application"."status_flags", ',') ~ '^$|^[A-Z][A-Z0-9_]{1,63}(,[A-Z][A-Z0-9_]{1,63})*$');
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_stage_trail_check' AND conrelid = '"seb_application"'::regclass
  ) THEN
    ALTER TABLE "seb_application" ADD CONSTRAINT "seb_application_stage_trail_check"
      CHECK (cardinality("seb_application"."stage_trail") <= 64
        AND array_position("seb_application"."stage_trail", NULL) IS NULL
        AND array_to_string("seb_application"."stage_trail", ',') ~ '^$|^[A-Z][A-Z0-9_]{1,63}(,[A-Z][A-Z0-9_]{1,63})*$');
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_recorded_values_check' AND conrelid = '"seb_application"'::regclass
  ) THEN
    ALTER TABLE "seb_application" ADD CONSTRAINT "seb_application_recorded_values_check"
      CHECK (jsonb_typeof("seb_application"."recorded_values") = 'object' AND octet_length("seb_application"."recorded_values"::text) <= 8192);
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_status_check' AND conrelid = '"seb_application"'::regclass
  ) THEN
    ALTER TABLE "seb_application" ADD CONSTRAINT "seb_application_status_check"
      CHECK ("seb_application"."status" IN ('DRAFT', 'IN_PIPELINE'));
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_phase_check' AND conrelid = '"seb_application"'::regclass
  ) THEN
    ALTER TABLE "seb_application" ADD CONSTRAINT "seb_application_phase_check"
      CHECK ("seb_application"."phase_number" >= 1);
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_version_kind_check' AND conrelid = '"seb_application_version"'::regclass
  ) THEN
    ALTER TABLE "seb_application_version" ADD CONSTRAINT "seb_application_version_kind_check"
      CHECK ("seb_application_version"."application_kind" ~ '^[A-Z][A-Z0-9_]{1,63}$');
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_version_phase_check' AND conrelid = '"seb_application_version"'::regclass
  ) THEN
    ALTER TABLE "seb_application_version" ADD CONSTRAINT "seb_application_version_phase_check"
      CHECK ("seb_application_version"."phase_number" >= 1);
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_programme_cycle_form_field_role_check' AND conrelid = '"seb_programme_cycle_form_field"'::regclass
  ) THEN
    ALTER TABLE "seb_programme_cycle_form_field" ADD CONSTRAINT "seb_programme_cycle_form_field_role_check"
      CHECK ("seb_programme_cycle_form_field"."role" IS NULL
        OR ("seb_programme_cycle_form_field"."role" = 'APPLICANT_DATE_OF_BIRTH' AND "seb_programme_cycle_form_field"."field_type" = 'DATE')
        OR ("seb_programme_cycle_form_field"."role" = 'SEED_FUND_REQUESTED_PAISE' AND "seb_programme_cycle_form_field"."field_key" = 'SEED_FUND_REQUESTED_PAISE' AND "seb_programme_cycle_form_field"."field_type" = 'MONEY_PAISE')
        OR ("seb_programme_cycle_form_field"."role" = 'LOAN_REQUESTED_PAISE' AND "seb_programme_cycle_form_field"."field_key" = 'LOAN_AMOUNT_REQUESTED_PAISE' AND "seb_programme_cycle_form_field"."field_type" = 'MONEY_PAISE'));
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_programme_cycle_version_pipeline_pin_check' AND conrelid = '"seb_programme_cycle_version"'::regclass
  ) THEN
    ALTER TABLE "seb_programme_cycle_version" ADD CONSTRAINT "seb_programme_cycle_version_pipeline_pin_check"
      CHECK (("seb_programme_cycle_version"."status" = 'DRAFT' AND "seb_programme_cycle_version"."pipeline_version" IS NULL)
        OR ("seb_programme_cycle_version"."status" <> 'DRAFT' AND "seb_programme_cycle_version"."pipeline_version" IS NOT NULL));
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_programme_cycle_version_months_check' AND conrelid = '"seb_programme_cycle_version"'::regclass
  ) THEN
    ALTER TABLE "seb_programme_cycle_version" ADD CONSTRAINT "seb_programme_cycle_version_months_check"
      CHECK ("seb_programme_cycle_version"."category_a_maximum_months" IS NULL OR "seb_programme_cycle_version"."category_a_maximum_months" >= 0);
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_event_from_status_check' AND conrelid = '"seb_application_event"'::regclass
  ) THEN
    ALTER TABLE "seb_application_event" ADD CONSTRAINT "seb_application_event_from_status_check"
      CHECK ("seb_application_event"."from_status" IS NULL OR "seb_application_event"."from_status" IN ('DRAFT', 'IN_PIPELINE'));
  END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'seb_application_event_to_status_check' AND conrelid = '"seb_application_event"'::regclass
  ) THEN
    ALTER TABLE "seb_application_event" ADD CONSTRAINT "seb_application_event_to_status_check"
      CHECK ("seb_application_event"."to_status" IS NULL OR "seb_application_event"."to_status" IN ('DRAFT', 'IN_PIPELINE'));
  END IF;
END $$;
