/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ShellAccountSessionsRouteImport } from './routes/_shell/account/sessions'
import { Route as ShellAppIndexRouteImport } from './routes/_shell/app/index'
import { Route as ShellAppEnterprisesIndexRouteImport } from './routes/_shell/app/enterprises/index'
import { Route as ShellAppEnterprisesIdRouteImport } from './routes/_shell/app/enterprises/$id'
import { Route as ShellAppEnterprisesNewRouteImport } from './routes/_shell/app/enterprises/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAccountSessionsRoute = ShellAccountSessionsRouteImport.update({
  id: '/account/sessions',
  path: '/account/sessions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppIndexRoute = ShellAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppEnterprisesIndexRoute =
  ShellAppEnterprisesIndexRouteImport.update({
    id: '/app/enterprises/',
    path: '/app/enterprises/',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellAppEnterprisesIdRoute = ShellAppEnterprisesIdRouteImport.update({
  id: '/app/enterprises/$id',
  path: '/app/enterprises/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppEnterprisesNewRoute = ShellAppEnterprisesNewRouteImport.update({
  id: '/app/enterprises/new',
  path: '/app/enterprises/new',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/sessions': typeof ShellAccountSessionsRoute
  '/app/': typeof ShellAppIndexRoute
  '/app/enterprises/$id': typeof ShellAppEnterprisesIdRoute
  '/app/enterprises/new': typeof ShellAppEnterprisesNewRoute
  '/app/enterprises/': typeof ShellAppEnterprisesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/sessions': typeof ShellAccountSessionsRoute
  '/app': typeof ShellAppIndexRoute
  '/app/enterprises/$id': typeof ShellAppEnterprisesIdRoute
  '/app/enterprises/new': typeof ShellAppEnterprisesNewRoute
  '/app/enterprises': typeof ShellAppEnterprisesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_shell/account/sessions': typeof ShellAccountSessionsRoute
  '/_shell/app/': typeof ShellAppIndexRoute
  '/_shell/app/enterprises/$id': typeof ShellAppEnterprisesIdRoute
  '/_shell/app/enterprises/new': typeof ShellAppEnterprisesNewRoute
  '/_shell/app/enterprises/': typeof ShellAppEnterprisesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/account/sessions'
    | '/app/'
    | '/app/enterprises/$id'
    | '/app/enterprises/new'
    | '/app/enterprises/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/account/sessions'
    | '/app'
    | '/app/enterprises/$id'
    | '/app/enterprises/new'
    | '/app/enterprises'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/sign-in'
    | '/sign-up'
    | '/_shell/account/sessions'
    | '/_shell/app/'
    | '/_shell/app/enterprises/$id'
    | '/_shell/app/enterprises/new'
    | '/_shell/app/enterprises/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/account/sessions': {
      id: '/_shell/account/sessions'
      path: '/account/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof ShellAccountSessionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/app/': {
      id: '/_shell/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof ShellAppIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/app/enterprises/': {
      id: '/_shell/app/enterprises/'
      path: '/app/enterprises'
      fullPath: '/app/enterprises/'
      preLoaderRoute: typeof ShellAppEnterprisesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/app/enterprises/$id': {
      id: '/_shell/app/enterprises/$id'
      path: '/app/enterprises/$id'
      fullPath: '/app/enterprises/$id'
      preLoaderRoute: typeof ShellAppEnterprisesIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/app/enterprises/new': {
      id: '/_shell/app/enterprises/new'
      path: '/app/enterprises/new'
      fullPath: '/app/enterprises/new'
      preLoaderRoute: typeof ShellAppEnterprisesNewRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAccountSessionsRoute: typeof ShellAccountSessionsRoute
  ShellAppIndexRoute: typeof ShellAppIndexRoute
  ShellAppEnterprisesIdRoute: typeof ShellAppEnterprisesIdRoute
  ShellAppEnterprisesNewRoute: typeof ShellAppEnterprisesNewRoute
  ShellAppEnterprisesIndexRoute: typeof ShellAppEnterprisesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAccountSessionsRoute: ShellAccountSessionsRoute,
  ShellAppIndexRoute: ShellAppIndexRoute,
  ShellAppEnterprisesIdRoute: ShellAppEnterprisesIdRoute,
  ShellAppEnterprisesNewRoute: ShellAppEnterprisesNewRoute,
  ShellAppEnterprisesIndexRoute: ShellAppEnterprisesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
