/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ShellAccountSessionsRouteImport } from './routes/_shell/account/sessions'
import { Route as ShellAppIndexRouteImport } from './routes/_shell/app/index'
import { Route as ShellAppCyclesRouteImport } from './routes/_shell/app/cycles'
import { Route as ShellAdminCyclesIndexRouteImport } from './routes/_shell/admin/cycles/index'
import { Route as ShellAdminCyclesIdRouteImport } from './routes/_shell/admin/cycles/$id'
import { Route as ShellAdminCyclesNewRouteImport } from './routes/_shell/admin/cycles/new'
import { Route as ShellAppApplicationsIndexRouteImport } from './routes/_shell/app/applications/index'
import { Route as ShellAppApplicationsIdRouteImport } from './routes/_shell/app/applications/$id'
import { Route as ShellAppApplicationsNewRouteImport } from './routes/_shell/app/applications/new'
import { Route as ShellAppEnterprisesIndexRouteImport } from './routes/_shell/app/enterprises/index'
import { Route as ShellAppEnterprisesIdRouteImport } from './routes/_shell/app/enterprises/$id'
import { Route as ShellAppEnterprisesNewRouteImport } from './routes/_shell/app/enterprises/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAccountSessionsRoute = ShellAccountSessionsRouteImport.update({
  id: '/account/sessions',
  path: '/account/sessions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppIndexRoute = ShellAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppCyclesRoute = ShellAppCyclesRouteImport.update({
  id: '/app/cycles',
  path: '/app/cycles',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminCyclesIndexRoute = ShellAdminCyclesIndexRouteImport.update({
  id: '/admin/cycles/',
  path: '/admin/cycles/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminCyclesIdRoute = ShellAdminCyclesIdRouteImport.update({
  id: '/admin/cycles/$id',
  path: '/admin/cycles/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminCyclesNewRoute = ShellAdminCyclesNewRouteImport.update({
  id: '/admin/cycles/new',
  path: '/admin/cycles/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppApplicationsIndexRoute =
  ShellAppApplicationsIndexRouteImport.update({
    id: '/app/applications/',
    path: '/app/applications/',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellAppApplicationsIdRoute = ShellAppApplicationsIdRouteImport.update({
  id: '/app/applications/$id',
  path: '/app/applications/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppApplicationsNewRoute = ShellAppApplicationsNewRouteImport.update({
  id: '/app/applications/new',
  path: '/app/applications/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppEnterprisesIndexRoute =
  ShellAppEnterprisesIndexRouteImport.update({
    id: '/app/enterprises/',
    path: '/app/enterprises/',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellAppEnterprisesIdRoute = ShellAppEnterprisesIdRouteImport.update({
  id: '/app/enterprises/$id',
  path: '/app/enterprises/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppEnterprisesNewRoute = ShellAppEnterprisesNewRouteImport.update({
  id: '/app/enterprises/new',
  path: '/app/enterprises/new',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/sessions': typeof ShellAccountSessionsRoute
  '/app/cycles': typeof ShellAppCyclesRoute
  '/app/': typeof ShellAppIndexRoute
  '/admin/cycles/$id': typeof ShellAdminCyclesIdRoute
  '/admin/cycles/new': typeof ShellAdminCyclesNewRoute
  '/app/applications/$id': typeof ShellAppApplicationsIdRoute
  '/app/applications/new': typeof ShellAppApplicationsNewRoute
  '/app/enterprises/$id': typeof ShellAppEnterprisesIdRoute
  '/app/enterprises/new': typeof ShellAppEnterprisesNewRoute
  '/admin/cycles/': typeof ShellAdminCyclesIndexRoute
  '/app/applications/': typeof ShellAppApplicationsIndexRoute
  '/app/enterprises/': typeof ShellAppEnterprisesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/sessions': typeof ShellAccountSessionsRoute
  '/app/cycles': typeof ShellAppCyclesRoute
  '/app': typeof ShellAppIndexRoute
  '/admin/cycles/$id': typeof ShellAdminCyclesIdRoute
  '/admin/cycles/new': typeof ShellAdminCyclesNewRoute
  '/app/applications/$id': typeof ShellAppApplicationsIdRoute
  '/app/applications/new': typeof ShellAppApplicationsNewRoute
  '/app/enterprises/$id': typeof ShellAppEnterprisesIdRoute
  '/app/enterprises/new': typeof ShellAppEnterprisesNewRoute
  '/admin/cycles': typeof ShellAdminCyclesIndexRoute
  '/app/applications': typeof ShellAppApplicationsIndexRoute
  '/app/enterprises': typeof ShellAppEnterprisesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_shell/account/sessions': typeof ShellAccountSessionsRoute
  '/_shell/app/cycles': typeof ShellAppCyclesRoute
  '/_shell/app/': typeof ShellAppIndexRoute
  '/_shell/admin/cycles/$id': typeof ShellAdminCyclesIdRoute
  '/_shell/admin/cycles/new': typeof ShellAdminCyclesNewRoute
  '/_shell/app/applications/$id': typeof ShellAppApplicationsIdRoute
  '/_shell/app/applications/new': typeof ShellAppApplicationsNewRoute
  '/_shell/app/enterprises/$id': typeof ShellAppEnterprisesIdRoute
  '/_shell/app/enterprises/new': typeof ShellAppEnterprisesNewRoute
  '/_shell/admin/cycles/': typeof ShellAdminCyclesIndexRoute
  '/_shell/app/applications/': typeof ShellAppApplicationsIndexRoute
  '/_shell/app/enterprises/': typeof ShellAppEnterprisesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/account/sessions'
    | '/app/cycles'
    | '/app/'
    | '/admin/cycles/$id'
    | '/admin/cycles/new'
    | '/app/applications/$id'
    | '/app/applications/new'
    | '/app/enterprises/$id'
    | '/app/enterprises/new'
    | '/admin/cycles/'
    | '/app/applications/'
    | '/app/enterprises/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/account/sessions'
    | '/app/cycles'
    | '/app'
    | '/admin/cycles/$id'
    | '/admin/cycles/new'
    | '/app/applications/$id'
    | '/app/applications/new'
    | '/app/enterprises/$id'
    | '/app/enterprises/new'
    | '/admin/cycles'
    | '/app/applications'
    | '/app/enterprises'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/sign-in'
    | '/sign-up'
    | '/_shell/account/sessions'
    | '/_shell/app/cycles'
    | '/_shell/app/'
    | '/_shell/admin/cycles/$id'
    | '/_shell/admin/cycles/new'
    | '/_shell/app/applications/$id'
    | '/_shell/app/applications/new'
    | '/_shell/app/enterprises/$id'
    | '/_shell/app/enterprises/new'
    | '/_shell/admin/cycles/'
    | '/_shell/app/applications/'
    | '/_shell/app/enterprises/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/account/sessions': {
      id: '/_shell/account/sessions'
      path: '/account/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof ShellAccountSessionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/app/': {
      id: '/_shell/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof ShellAppIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/app/cycles': {
      id: '/_shell/app/cycles'
      path: '/app/cycles'
      fullPath: '/app/cycles'
      preLoaderRoute: typeof ShellAppCyclesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/cycles/': {
      id: '/_shell/admin/cycles/'
      path: '/admin/cycles'
      fullPath: '/admin/cycles/'
      preLoaderRoute: typeof ShellAdminCyclesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/cycles/$id': {
      id: '/_shell/admin/cycles/$id'
      path: '/admin/cycles/$id'
      fullPath: '/admin/cycles/$id'
      preLoaderRoute: typeof ShellAdminCyclesIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/cycles/new': {
      id: '/_shell/admin/cycles/new'
      path: '/admin/cycles/new'
      fullPath: '/admin/cycles/new'
      preLoaderRoute: typeof ShellAdminCyclesNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/app/applications/': {
      id: '/_shell/app/applications/'
      path: '/app/applications'
      fullPath: '/app/applications/'
      preLoaderRoute: typeof ShellAppApplicationsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/app/applications/$id': {
      id: '/_shell/app/applications/$id'
      path: '/app/applications/$id'
      fullPath: '/app/applications/$id'
      preLoaderRoute: typeof ShellAppApplicationsIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/app/applications/new': {
      id: '/_shell/app/applications/new'
      path: '/app/applications/new'
      fullPath: '/app/applications/new'
      preLoaderRoute: typeof ShellAppApplicationsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/app/enterprises/': {
      id: '/_shell/app/enterprises/'
      path: '/app/enterprises'
      fullPath: '/app/enterprises/'
      preLoaderRoute: typeof ShellAppEnterprisesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/app/enterprises/$id': {
      id: '/_shell/app/enterprises/$id'
      path: '/app/enterprises/$id'
      fullPath: '/app/enterprises/$id'
      preLoaderRoute: typeof ShellAppEnterprisesIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/app/enterprises/new': {
      id: '/_shell/app/enterprises/new'
      path: '/app/enterprises/new'
      fullPath: '/app/enterprises/new'
      preLoaderRoute: typeof ShellAppEnterprisesNewRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAccountSessionsRoute: typeof ShellAccountSessionsRoute
  ShellAppCyclesRoute: typeof ShellAppCyclesRoute
  ShellAppIndexRoute: typeof ShellAppIndexRoute
  ShellAdminCyclesIdRoute: typeof ShellAdminCyclesIdRoute
  ShellAdminCyclesNewRoute: typeof ShellAdminCyclesNewRoute
  ShellAppApplicationsIdRoute: typeof ShellAppApplicationsIdRoute
  ShellAppApplicationsNewRoute: typeof ShellAppApplicationsNewRoute
  ShellAppEnterprisesIdRoute: typeof ShellAppEnterprisesIdRoute
  ShellAppEnterprisesNewRoute: typeof ShellAppEnterprisesNewRoute
  ShellAdminCyclesIndexRoute: typeof ShellAdminCyclesIndexRoute
  ShellAppApplicationsIndexRoute: typeof ShellAppApplicationsIndexRoute
  ShellAppEnterprisesIndexRoute: typeof ShellAppEnterprisesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAccountSessionsRoute: ShellAccountSessionsRoute,
  ShellAppCyclesRoute: ShellAppCyclesRoute,
  ShellAppIndexRoute: ShellAppIndexRoute,
  ShellAdminCyclesIdRoute: ShellAdminCyclesIdRoute,
  ShellAdminCyclesNewRoute: ShellAdminCyclesNewRoute,
  ShellAppApplicationsIdRoute: ShellAppApplicationsIdRoute,
  ShellAppApplicationsNewRoute: ShellAppApplicationsNewRoute,
  ShellAppEnterprisesIdRoute: ShellAppEnterprisesIdRoute,
  ShellAppEnterprisesNewRoute: ShellAppEnterprisesNewRoute,
  ShellAdminCyclesIndexRoute: ShellAdminCyclesIndexRoute,
  ShellAppApplicationsIndexRoute: ShellAppApplicationsIndexRoute,
  ShellAppEnterprisesIndexRoute: ShellAppEnterprisesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
